version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7.7
    steps:
    - checkout
    - run:
        command: git clone https://github.com/Raybeam/lumen-test-airflow /home/circleci/lumen-test-airflow
        name: Set up Airflow
    - run:
        command: |-
          cd /home/circleci/lumen-test-airflow
          python -m venv .
          echo "export AIRFLOW_HOME=$PWD" >> bin/activate
          source bin/activate
          pip install -r requirements.txt
          pip install -r /home/circleci/project/requirements.txt
          airflow initdb
          mkdir ./plugins/ 
          ln -s /home/circleci/project/plugins/lumen_plugin ./plugins/
          airflow create_user -r Admin -u admin -e admin@example.com -f admin -l user -p admin
          python -m unittest discover -s plugins/lumen_plugin/tests/ -p '*_test.py'
    - run:
        command: |-
          echo "TRIGGERER: ${CIRCLE_USERNAME}"
          echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
          echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
          echo "BRANCH: ${CIRCLE_BRANCH}"
          echo "RUNNING JOB: ${CIRCLE_JOB}"
          echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
          echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
        name: Show some of the CircleCI runtime env vars
    - run:
        command: |-
          echo "uname:" $(uname -a)
          echo "arch: " $(arch)
        name: Show system information
workflows:
  test:
    jobs:
    - build
  version: 2

